#!/usr/bin/env bash

alias gs='git status -s'
alias gcaa='git commit -a --amend --reuse-message=HEAD'
alias ls='ls --color'
alias mv='mv -v'
alias rm='rm -v'
alias cp='cp -v'
alias aptu="sudo apt-get update && sudo apt-get upgrade"
alias bashreset='source ~/.bashrc'
# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# clone a git repo, cd into it, install yarn dependencies
function clone() {
    git clone --depth=1 $1
    cd $(basename ${1%.*})
    yarn install
}

# `a` with no arguments opens the current directory in Atom Editor, otherwise
# opens the given location
function a() {
	if [ $# -eq 0 ]; then
		atom .;
	else
		atom "$@";
	fi;
}
